environment:
  nodejs_version: "8.10"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn

test_script:
  - node --version
  - yarn --version
  - yarn lint
  - yarn test
  - yarn build

build: off
